### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by agatocherry** [agatocherry/webserv#4]
- [x] Est-ce qu'un socket peut ecouter plusieurs ports ?
- [x] Que veut dire "upload files" dans le sujet
- [x] Que veut dire "HTTP redirection" dans le sujet
- [x] Qu'est-ce que "chunked request" dans le sujet ?
- [x] Faire une explication de toute la partie CGI du sujet ?
- [x] Quesqu'il se passe si ont depasse le client body buffer_size ? Ou vas le fichier tmp ?

**Comment by shell02** [comment]
1: Non, une fois que bind est utilise sur un socket, on ne peut pas utilise une deuxieme fois bind
2: Toujours pas clair.
3: juste passer de http://example.com a ./data/example.com
4: Chunked request est une facon d'envoyer un message en plusieurs fois, avec : [nombre de caracteres]\r\n[message]
par example
6\r\n
Hello \r\n
7\r\n
World !\r\n
0\r\n
\r\n
5: pour savoir quand utiliser le script cgi, il faut definir un dossier ou toutes les demandes passeront par le script cgi ou il faut definir une extension (par exemple ".cgi") qui utilisera tout le temps le script cgi. Ensuite, il faut faire appel au script (execve) avec les bonnes variables d'environnement definies et le script cgi ecrit la reponse a envoyer dans stdout (redirection a faire puis a envoyer au client)
6: faire une erreur, pas de fichier temp
