### ISSUE TITLE
Test Nginx

### ISSUE THREAD

**Issue by agatocherry** [agatocherry/webserv#5]
- [x] Envoyer un signal au serveur depuis le terminal, afin d'utiliser le server_name
- [x] Mettre plusieurs ports differents dans la directive "listen" (est-ce que les deux ports sont ecoutes ou est-ce qu'il y a une erreur...?)
- [x] Comment recuperer les requetes et les reponses depuis le navigateur et le serveur NGINX

**Comment by shell02** [comment]
Sur Mozilla : 
- clic droit et appuyer sur Inspecter
- appuyer sur l'onglet reseau
- cliquer sur une requete et cocher texte brut (vers la droite)
