### ISSUE TITLE
Class ConfigInfo

### ISSUE THREAD

**Issue by shell02** [agatocherry/webserv#8]
- [x] Modifier Location struct pour un vector dans ServerInfo
- [x] Faire la fonction qui renvoi le max_fd dans ConfigInfo

**Comment by agatocherry** [comment]
Coucou @shell02, dis quand tu fais référence au _size (fait reference au nombre de listen), tu parle du _size sur la class [ConfigInfo](https://github.com/agatocherry/webserv/blob/8-class-configinfo/includes/ConfigInfo.hpp) ou [Server](https://github.com/agatocherry/webserv/blob/8-class-configinfo/includes/Server.hpp) ?
